#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 21 常見問題與建議 (2)
# Url: https://ithelp.ithome.com.tw/articles/10193946
# Licence: MIT
#####################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: err-limit-nginx
spec:
    replicas: 1
    template:
      metadata:
        labels: 
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: 100Gi

