#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 21 常見問題與建議 (2)
# Url: https://ithelp.ithome.com.tw/articles/10193946
# Licence: MIT
#####################################

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
    pods: 1